Repository Data-Science-Brigade/modelo-epidemiologico-sc, pull requests merged in 2021-07, with the labels that each got.

#39 Feature/natalia independent inference
  epiCata/R/data.R
  epiCata/R/utils.R
  install_dependencies.R
  run_health_regions_independently.R
  run_macro_regions_independently.R
Labels: feature

#38 🐛base-reported was still using old EpidemicStart parameter
  epiCata/inst/extdata/stan-models/base-reported.stan
Labels: bug, enhancement

#46 ⚙️ Split microregions in two scripts so they can be run in parallel
  combine_independent_results.R
  run_health_regions_A.R
  run_health_regions_B.R
Labels: enhancement

#41 Consider previously trained model for each region
  combine_independent_results.R
  epiCata/R/model.R
  epiCata/R/utils.R
  run_health_regions_A.R
  run_health_regions_B.R
  run_health_regions_independently.R
  run_macro_regions_independently.R
Labels: bug, feature

#54 Feature/natalia update start date and reparametrize si
  epiCata/R/preprocessing.R
  epiCata/inst/extdata/stan-models/base-reported.stan
  run_health_regions_independently.R
Labels: modelling
